[build]
  command = "rm -rf .next && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  SECRETS_SCAN_OMIT_KEYS = "RESEND_API_KEY, APIFY_USER_ID, API_GROQ_KEY, BRAVE_API_KEY, API_KEY_APIFY"
  SECRETS_SCAN_OMIT_PATHS = ".next, .netlify"

[[plugins]]
  package = "@netlify/plugin-nextjs"

